### ISSUE TITLE
Create Profiledit Page (username, profilepic)

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/client#72]
Create  Profiledit Page (username, profilepic)

**Comment by awhoa** [comment]
done

**Comment by melihcatal** [comment]
@awhoa Could you please reference to the commit that closes the issue?

**Comment by awhoa** [comment]
Will do it tomorrow morning, thanks

Cheers

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by awhoa** [comment]
commit 5c278d2f3dd1876807045209cd992ebfe9e13e29
